# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(name: "Incognito",      email: "incognito@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "Ver",            email: "ver@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "Foolishness",    email: "foolishness@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "flamewheel",     email: "flamewheel@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "GMarshal",       email: "gmarshal@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "Qatol",          email: "qatol@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "dreamflower",    email: "dreamflower@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "Radfield",       email: "radfield@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "Palmar",         email: "palmar@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "prplhz",         email: "prplhz@example.com", password: "foobar", password_confirmation: "foobar")

User.create(name: "Protactinium",   email: "protactinium@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "Chezinu",        email: "chezinu@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "Ace",            email: "ace@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "BloodyC0bbler",  email: "bloodyc0bbler@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "gonzaw",         email: "gonzaw@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "syllogism",      email: "syllogism@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "Toadesstern",    email: "toadesstern@example.com", password: "foobar", password_confirmation: "foobar")

User.create(name: "Meapak_Ziphh",   email: "meapak_ziphh@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "Mr. Wiggles",    email: "mr.wiggles@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "Hesmyrr",        email: "hesmyrr@example.com", password: "foobar", password_confirmation: "foobar")
User.create(name: "iGrok",          email: "igrok@example.com", password: "foobar", password_confirmation: "foobar")

User.find(1).topics.create(title: "A")
User.find(2).topics.create(title: "B")
User.find(3).topics.create(title: "C")
User.find(4).topics.create(title: "D")
User.find(5).topics.create(title: "E")
User.find(6).topics.create(title: "F")
User.find(7).topics.create(title: "G")
User.find(8).topics.create(title: "H")
User.find(9).topics.create(title: "I")

User.find(1).posts.create(content: "Hello World", topic_id: 1)
User.find(2).posts.create(content: "Hello World", topic_id: 2)
User.find(3).posts.create(content: "Hello World", topic_id: 3)
User.find(4).posts.create(content: "Hello World", topic_id: 4)
User.find(5).posts.create(content: "Hello World", topic_id: 5)
User.find(6).posts.create(content: "Hello World", topic_id: 6)
User.find(7).posts.create(content: "Hello World", topic_id: 7)
User.find(8).posts.create(content: "Hello World", topic_id: 8)
User.find(9).posts.create(content: "Hello World", topic_id: 9)

User.find(1).hosted_games.create(player_cap: 30, topic_id: 1, mini: false, invite: false, category: "Normal")
User.find(2).hosted_games.create(player_cap: 30, topic_id: 2, mini: false, invite: false, category: "Normal")
User.find(3).hosted_games.create(player_cap: 30, topic_id: 3, mini: false, invite: false, category: "Normal")
User.find(4).hosted_games.create(player_cap: 30, topic_id: 4, mini: false, invite: false, category: "Themed")
User.find(5).hosted_games.create(player_cap: 11, topic_id: 5, mini: true, invite: false, category: "Themed")
User.find(6).hosted_games.create(player_cap: 11, topic_id: 6, mini: true, invite: false, category: "Themed")
User.find(7).hosted_games.create(player_cap: 11, topic_id: 7, mini: true, invite: false, category: "Normal")
User.find(8).hosted_games.create(player_cap: 11, topic_id: 8, mini: true, invite: false, category: "Normal")
User.find(9).hosted_games.create(player_cap: 11, topic_id: 9, mini: true, invite: false, category: "Normal")
